# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Böddenstedt Audio Guide
email: audio@boeddenstedt.de
description: > # this means to ignore newlines until "baseurl:"
  Eine Audiotour durch das Golddorf Böddenstedt in der Lüneburger Heide.
baseurl: "/" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "http://boedde.qnib.org" # the base hostname & protocol for your site
logo: "/assets/img/logo/boeddenstedt-audio-guide.png"
twitter_username: CQnib
github_username:  ChristianKniep
menu_heading: "Wähle einen Stop:"
index_page_text: "Wähle einen Stop um zu beginnen:"
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
